language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.6
notifications:
    email: false


before_install:
    - pip install black
install:
    - pip install .

script:
    - black --check .
    - python -m pytest
